services:
    azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        container_name: azurite-${COMPOSE_PROJECT_NAME}
        ports:
            - "10000:10000"
            - "10001:10001"
            - "10002:10002"