name: Safe Bookstore build and test

on:
  pull_request:
    types: [opened, edited] 

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: v5-update-build
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore tools
      working-directory: ./update
      run: dotnet tool restore

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      working-directory: ./update
      run: dotnet run devopstests

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      working-directory: ./update
      run: dotnet run bundle